name: RefBasedAssembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - abra2=2.23
  - alsa-lib=1.2.6.1
  - bcftools=1.15.1
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.36.1
  - bioawk=1.0
  - bowtie2=2.4.4
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - coreutils=9.1
  - curl=7.83.1
  - expat=2.4.8
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freebayes=0.9.21.7
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=12.1.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=12.1.0
  - giflib=5.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=12.1.0
  - harfbuzz=5.1.0
  - htslib=1.15.1
  - icu=70.1
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libsanitizer=12.1.0
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.1.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.3
  - nextflow=22.04.0
  - openjdk=17.0.3
  - openssl=1.1.1q
  - pango=1.50.9
  - pcre=8.45
  - pcre2=10.37
  - perl=5.32.1
  - picard=2.27.4
  - pip=22.2.2
  - pixman=0.40.0
  - primerclip=0.3.8
  - pthread-stubs=0.4
  - python=3.9.13
  - python_abi=3.9
  - r-base=4.2.1
  - readline=8.1.2
  - samtools=1.15.1
  - sed=4.8
  - setuptools=64.0.3
  - sqlite=3.39.2
  - sysroot_linux-64=2.12
  - tbb=2020.2
  - tk=8.6.12
  - tktable=2.10
  - trimmomatic=0.39
  - tzdata=2022b
  - vcftools=0.1.16
  - wheel=0.37.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pyvcf3==1.0.3
